# Generated by Django 3.1.7 on 2021-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaperApp', '0005_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
