# Generated by Django 3.1.7 on 2021-04-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaperApp', '0006_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(through='NewsPaperApp.PostCategory', to='NewsPaperApp.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
